stm: STMList.hs TestSTMLL.hs
	/home/ardubois/Desktop/jonathas/ghc/inplace/bin/ghc-stage2 --make -rtsopts -threaded TestSTMLL.hs

cleanstm:
	rm *.hi
	rm *.o
	rm TestSTMLL

ota: OTATOLinkedList.hs TestOTATOLL.hs
	/home/ardubois/Desktop/jonathas/ghc/inplace/bin/ghc-stage2 --make -rtsopts -threaded TestOTATOLL.hs

cleanota:
	rm *.hi
	rm *.o
	rm TestOTATOLL
	
cas: CASList.hs TestCASLL.hs
	/home/ardubois/Desktop/jonathas/ghc/inplace/bin/ghc-stage2 --make -rtsopts -threaded TestCASLL.hs

cleancas:
	rm *.hi
	rm *.o
	rm TestCASLL
