stm: TestSTMSet.hs STMSet.hs 
	/home/ardubois/Desktop/jonathas/ghc/inplace/bin/ghc-stage2 --make -rtsopts -threaded TestSTMSet.hs

cleanstm:
	rm *.hi
	rm *.o
	rm TestSTMSet

ota: TestOTASet.hs OTASet.hs
	/home/ardubois/Desktop/jonathas/ghc/inplace/bin/ghc-stage2 --make -rtsopts -threaded TestOTASet.hs

cleanota:
	rm *.hi
	rm *.o
	rm TestOTASet
