stm: IDSTM.hs
	/home/ardubois/Desktop/jonathas/ghc/inplace/bin/ghc-stage2 --make -rtsopts -threaded IDSTM.hs

cleanstm:
	rm *.hi
	rm *.o
	rm IDSTM

cas: IDCAS.hs
	/home/ardubois/Desktop/jonathas/ghc/inplace/bin/ghc-stage2 --make -rtsopts -threaded IDCAS.hs

cleancas:
	rm *.hi
	rm *.o
	rm IDCAS

ota: IDOTA.hs
	/home/ardubois/Desktop/jonathas/ghc/inplace/bin/ghc-stage2 --make -rtsopts -threaded IDOTA.hs

cleanota:
	rm *.hi
	rm *.o
	rm IDOTA
